name: Extension tests

on:
  pull_request:
    branches:
      - main

jobs:
  extension-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./extension/.nvmrc

      - name: Install dependencies
        working-directory: ./extension
        run: npm ci

      - name: Run tests
        working-directory: ./extension
        run: npm run test:coverage

      - name: Publish tests results and badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure()
        with:
          result-type: statements
          upload-badge: false
          badge-path: ./doc/badge.svg

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: doc/badge.svg extension/test-output.json
